In [1]:

# Data Normalization Techniques
#
# In this lab we'll learn about various data normalization techniques, with
# both their implementation and commonly used library functions:
#
# 1. Min-max normalization
# 2. Z-score normalization
# 3. Decimal Scaling Normalization

# Data Normalization Techniques Lab

This lab explores three common data normalization techniques: Min-Max scaling, Z-Score normalization, and Decimal Scaling. You will learn how to implement each technique manually and also how to use the corresponding functions from the scikit-learn library for Min-Max and Z-Score normalization. The lab demonstrates these techniques using the "LotArea" column from a housing dataset.

In [2]:
# Download the dataset file to local storage to current directory (from publicly
# shared drive file)
#
# Original source:
# https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques
!gdown 1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP

Downloading...
From: https://drive.google.com/uc?id=1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP
To: /content/housing.csv
100% 461k/461k [00:00<00:00, 45.8MB/s]

In [3]:
# Import required libraries
import pandas as pd

from sklearn.preprocessing import MinMaxScaler # min-max
from sklearn.preprocessing import StandardScaler # z-score
import math # used to calculate no. of digits (floor, log) for decimal scaling

In [4]:
import pandas as pd

# Load the dataset file into memory
DATASET_PATH = "./housing.csv"
df = pd.read_csv(DATASET_PATH)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
# 1. Min-max normalization
#
# Min-max normalization is a normalization technique where we consider the
# original scale of the data as the min and max values of the attribute
# and scale all its values to a given range (a to b ; where a < b)

In [6]:
# Let us consider the LotArea column
A = df["LotArea"]

# Calculating the column's minimum and maximum value
minA = A.min()
maxA = A.max()

# Displaying the current min-max values
print("Current min:", minA)
print("Current max:", maxA)

Current min: 1300
Current max: 215245

In [7]:
# As we can see here, the range of value here is really high and it would be
# better if we normalize this column

# Calculating the range/difference of min-max
rangeA = maxA - minA

# Choosing a new min/max scale
newMin = 1
newMax = 100

# Normalizing the value between newMin and newMax
#
# All values of df are subtracted by minA then divided by rangeA, the resulting
# values then get multiplied by newMax-newMin and added to newMin

# Formula
# v' = ((v-minA)/rangeA) * (newMax - newMin) + newMin
A_normalized = ((df["LotArea"] - minA) / rangeA) * (newMax - newMin) + newMin

# Confirming that the min/max values have been followed
print("New min:", A_normalized.min())
print("New max:", A_normalized.max())

# Displaying the normalized output
A_normalized

# A simple intuitive explanation for the working of min-max normalization -
#
# Take a rough number line on a sheet and mark points to visualize and
# intuitively understand the above equation better:
#
# Start with roughly marking the the absolute min and max and mark a point
# between the min and max to denote the value, in our case of df["LotArea"]
#
# df["LotArea"] - minA -> How far is the value from its attribute's min
#
# rangeA -> The maximum possible value for (df["LotArea"] - minA)
#
# df["LotArea"] - minA) / rangeA -> The normalized value of the attribute b/w
# 0 and 1
#
# (newMax - newMin) -> Multiplying the normalized values between 0 and 1
# gives us the values for the new range of values
#
# The new range would be between 0 and newMax after multiplication, therefore
# adding newMin to fix that

New min: 1.0
New max: 100.0

0       4.308561
1       4.840707
2       5.604221
3       4.817570
4       6.997055
          ...
1455    4.061922
1456    6.494987
1457    4.582500
1458    4.894847
1459    4.996649
Name: LotArea, Length: 1460, dtype: float64

In [8]:
# @title
# Self-exploration: You could pick a different column such as the "Year" column,
# where it might make more sense to have a normalized scale for prediction than
# a value such as 2000 or 1900 for example

# ...
B = df['YrSold']

minB = B.min()
maxB = B.max()

print(f"Current Min: {minB}\nCurrent Max: {maxB}")

rangeB = maxB - minB

B_normalized = ((df['YrSold']-minB)/rangeB) * (newMax-newMin) + newMin

# Confirming that the min/max values have been followed
print("New min:", B_normalized.min())
print("New max:", B_normalized.max())

B_normalized

Current Min: 2006
Current Max: 2010
New min: 1.0
New max: 100.0

0        50.50
1        25.75
2        50.50
3         1.00
4        50.50
         ...
1455     25.75
1456    100.00
1457    100.00
1458    100.00
1459     50.50
Name: YrSold, Length: 1460, dtype: float64

In [9]:
# Min-max normalization can be done using a few lines via sklearn's MinMaxScaler
# that's a part of its preprocessing package
#
# It has two phases of usage, fit and transform -
#
# fit() is generally used to calculate and set the min-max values for the
# normalization phase
#
# transform() is generally used to transform a
#
# Prototype (parameters, default values):
# (feature_range: Any = (0, 1), *, copy: bool = True, clip: bool = False)
#
# feature_range is the range to which we wish to normalize
#
# copy when true does not do inplace replacement in the column values while
# running transform(...) by default, can be changed to false for inplace
# replacement
#
# clip when true, ensures that a new data point which wasn't passed to
# fit(...) for training, does not go beyond the range of the training data
minMaxScaler = MinMaxScaler(feature_range=(newMin, newMax))

# Calculates and sets variables for normalization
minMaxScaler.fit(A.to_frame())

# Performs the actual transformation on the data as np array
transformed_output = minMaxScaler.transform(A.to_frame())

# Converting the transformed column to do
transformed_column = pd.DataFrame(transformed_output)
transformed_column

             0
0     4.308561
1     4.840707
2     5.604221
3     4.817570
4     6.997055
...        ...
1455  4.061922
1456  6.494987
1457  4.582500
1458  4.894847
1459  4.996649

[1460 rows x 1 columns]

In [10]:
# 2. Z-score normalization
#
# Z-score normalization is a normalization technique that takes into
# consideration mean as the center point and scales to the value/units of
# standard deviation (considers the general variance of the dataset).
#
# This kind of normalization is generally considered better because its less
# affected by outliers which would be a problem in case of min-max scaling
# as an unusual point that's very far would increase the scale to an extent
# that legitimate points within reasonable limits would be considered
# insignificant
#
# Mathematically, for every point 'a' in attribute set 'A',
# a_std = (a - A_mean / A_SD)

In [11]:
# Let us consider the LotArea column
A = df["LotArea"]

# Calculate the z-normalized value for column/series A
A_z_normalized = (A - A.mean()) / A.std()
A_z_normalized

0      -0.207071
1      -0.091855
2       0.073455
3      -0.096864
4       0.375020
          ...
1455   -0.260471
1456    0.266316
1457   -0.147760
1458   -0.080133
1459   -0.058092
Name: LotArea, Length: 1460, dtype: float64

In [12]:
# Sklearn's pre-processing package provides a function to perform this with some
# additional functionality which could be used for code simplicity
#
#
standard_scaler = StandardScaler()
A_z_normalized = standard_scaler.fit_transform(A.to_frame())
A_z_normalized

array([[-0.20714171],
       [-0.09188637],
       [ 0.07347998],
       ...,
       [-0.14781027],
       [-0.08016039],
       [-0.05811155]])

In [13]:
# 3. Decimal Scaling Normalization
#
# Decimal Scaling Normalization is a form of normalization where we shift the
# decimal point of the number with respect the largest number in the dataset
# in terms of its absolute value, such that all numbers are between (-1, 1)
#
# We do so using the following steps:
#
# 1. To do so we first find the largest absolute number in the dataset
# 2. Calculate its number of digits (j)
# 3. Calculate 10^(j+1)
# 4. Divide the value obtained in step 3 to normalize it
#
# The value of such normalization is in the range -1 to 1 and by definition no
# value can be 1 or -1 (i.e. if the largest number is 1000, it implies that it
# would be normalized to 0.1 and not 1.0) [range exclusive]

In [14]:
# Let us consider the LotArea column again
A = df["LotArea"]

# Calculating the maximum absolute value of column/attribute A
maxAbsA = A.abs().max()
print(maxAbsA)

# Calculating the number of digits in the maximum absolute value of A
digitsMaxAbsA = math.floor(math.log(maxAbsA, 10)) + 1
print(digitsMaxAbsA)

A_dec_normalized = df["LotArea"] / 10**(digitsMaxAbsA + 1)
A_dec_normalized

215245
6

0       0.000845
1       0.000960
2       0.001125
3       0.000955
4       0.001426
          ...
1455    0.000792
1456    0.001318
1457    0.000904
1458    0.000972
1459    0.000994
Name: LotArea, Length: 1460, dtype: float64

In [15]:
# The last method as it appears isn't widely used, therefore there are no
# standard popular libraries that implement it

In [16]:
df.to_excel('final_dataset.xlsx',index=False)