In [ ]:
# Data Aggregation Techniques
#
# In this lab we'll learn about various data aggregation techniques through
# different scenarios to understand the practical applications of these methods

In [ ]:
# Download the dataset file to local storage to current directory (from publicly
# shared drive file)
#
# Original source:
# https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques
!gdown 1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP

Downloading...
From: https://drive.google.com/uc?id=1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP
To: /content/housing.csv
100% 461k/461k [00:00<00:00, 14.1MB/s]

In [ ]:
# Import required libraries
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import math # use

In [ ]:
# Load the dataset file into memory
DATASET_PATH = "./housing.csv"
df = pd.read_csv(DATASET_PATH)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
# We'll be performing aggregation functions on both grouped and un-grouped data
#
# For grouped data, we'll be considering the neighborhood for our aggregation
# based analysis ahead
#
grouped_df = df.groupby('Neighborhood')
grouped_df.describe()

                 Id                                                         \
              count        mean         std    min     25%    50%      75%
Neighborhood
Blmngtn        17.0  773.941176  370.871688  220.0  466.00  791.0  1020.00
Blueste         2.0  778.500000  252.437121  600.0  689.25  778.5   867.75
BrDale         16.0  719.187500  443.481412  226.0  332.00  578.5  1133.75
BrkSide        58.0  734.724138  435.850884   10.0  405.00  696.0  1139.00
ClearCr        28.0  604.928571  382.491339   70.0  278.00  523.5   834.00
CollgCr       150.0  726.840000  445.513942    1.0  303.25  755.0  1079.75
Crawfor        51.0  801.078431  432.064247    4.0  451.50  861.0  1177.00
Edwards       100.0  762.930000  413.290620   40.0  407.25  732.0  1123.25
Gilbert        79.0  749.151899  426.017488   51.0  364.00  795.0  1121.00
IDOTRR         37.0  597.540541  430.578396   22.0  269.00  558.0   917.00
MeadowV        17.0  733.000000  426.120142   24.0  435.00  650.0  1040.00
Mitchel        49.0  759.102041  429.507918    6.0  421.00  784.0  1139.00
NAmes         225.0  737.995556  431.303283   15.0  367.00  761.0  1104.00
NPkVill         9.0  781.444444  490.184432  127.0  505.00  676.0  1161.00
NWAmes         73.0  822.452055  413.706520    8.0  488.00  860.0  1160.00
NoRidge        41.0  815.268293  411.208890    5.0  518.00  760.0  1183.00
NridgHt        77.0  609.714286  401.319038   12.0  321.00  553.0   927.00
OldTown       113.0  694.194690  435.761891    9.0  305.00  638.0  1077.00
SWISU          25.0  841.240000  363.138091  268.0  566.00  841.0  1101.00
Sawyer         74.0  715.851351  387.737932   11.0  466.25  751.0  1003.25
SawyerW        59.0  665.152542  407.841281   19.0  283.00  743.0   944.50
Somerst        86.0  755.744186  418.889096    7.0  402.50  764.5  1091.50
StoneBr        25.0  669.520000  345.687253   59.0  471.00  689.0   770.00
Timber         38.0  787.026316  413.047245   42.0  472.50  799.5  1145.00
Veenker        11.0  618.909091  459.322208    2.0  244.00  673.0  1003.00

                     MSSubClass              ...   YrSold         SalePrice  \
                 max      count        mean  ...      75%     max     count
Neighborhood                                 ...
Blmngtn       1416.0       17.0  114.117647  ...  2009.00  2010.0      17.0
Blueste        957.0        2.0  160.000000  ...  2008.75  2009.0       2.0
BrDale        1379.0       16.0  160.000000  ...  2009.00  2010.0      16.0
BrkSide       1444.0       58.0   49.741379  ...  2009.00  2010.0      58.0
ClearCr       1288.0       28.0   52.500000  ...  2009.00  2010.0      28.0
CollgCr       1448.0      150.0   43.300000  ...  2009.00  2010.0     150.0
Crawfor       1458.0       51.0   58.235294  ...  2008.00  2010.0      51.0
Edwards       1460.0      100.0   56.800000  ...  2009.00  2010.0     100.0
Gilbert       1456.0       79.0   58.227848  ...  2009.00  2010.0      79.0
IDOTRR        1386.0       37.0   53.648649  ...  2009.00  2010.0      37.0
MeadowV       1450.0       17.0  163.529412  ...  2009.00  2010.0      17.0
Mitchel       1454.0       49.0   56.632653  ...  2009.00  2010.0      49.0
NAmes         1459.0      225.0   38.777778  ...  2009.00  2010.0     225.0
NPkVill       1432.0        9.0  142.222222  ...  2009.00  2010.0       9.0
NWAmes        1457.0       73.0   44.589041  ...  2009.00  2010.0      73.0
NoRidge       1427.0       41.0   53.658537  ...  2009.00  2010.0      41.0
NridgHt       1438.0       77.0   62.077922  ...  2009.00  2010.0      77.0
OldTown       1439.0      113.0   66.238938  ...  2009.00  2010.0     113.0
SWISU         1400.0       25.0   72.200000  ...  2009.00  2010.0      25.0
Sawyer        1446.0       74.0   40.608108  ...  2009.00  2010.0      74.0
SawyerW       1414.0       59.0   58.220339  ...  2009.00  2010.0      59.0
Somerst       1455.0       86.0   74.186047  ...  2009.00  2010.0      86.0
StoneBr       1362.0       25.0   83.200000  ...  2009.00  2010.0      25.0
Timber        1397.0       38.0   39.473684  ...  2009.00  2010.0      38.0
Veenker       1254.0       11.0   61.818182  ...  2007.50  2008.0      11.0

                                                                           \
                       mean            std       min        25%       50%
Neighborhood
Blmngtn       194870.882353   30393.229219  159895.0  174000.00  191000.0
Blueste       137500.000000   19091.883092  124000.0  130750.00  137500.0
BrDale        104493.750000   14330.176493   83000.0   91000.00  106000.0
BrkSide       124834.051724   40348.689270   39300.0  100500.00  124300.0
ClearCr       212565.428571   50231.538993  130000.0  183750.00  200250.0
CollgCr       197965.773333   51403.666438  110000.0  152958.75  197200.0
Crawfor       210624.725490   68866.395472   90350.0  159250.00  200624.0
Edwards       128219.700000   43208.616459   58500.0  101500.00  121750.0
Gilbert       192854.506329   35986.779085  141000.0  174000.00  181000.0
IDOTRR        100123.783784   33376.710117   34900.0   81000.00  103000.0
MeadowV        98576.470588   23491.049610   75000.0   83500.00   88000.0
Mitchel       156270.122449   36486.625334   84500.0  131000.00  153500.0
NAmes         145847.080000   33075.345450   87500.0  127500.00  140000.0
NPkVill       142694.444444    9377.314529  127500.0  140000.00  146000.0
NWAmes        189050.068493   37172.218106   82500.0  165150.00  182900.0
NoRidge       335295.317073  121412.658640  190000.0  265000.00  301500.0
NridgHt       316270.623377   96392.544954  154000.0  253293.00  315000.0
OldTown       128225.300885   52650.583185   37900.0  105900.00  119000.0
SWISU         142591.360000   32622.917679   60000.0  128000.00  139500.0
Sawyer        136793.135135   22345.129157   62383.0  127250.00  135000.0
SawyerW       186555.796610   55651.997820   76000.0  145500.00  179900.0
Somerst       225379.837209   56177.555888  144152.0  177975.00  225500.0
StoneBr       310499.000000  112969.676640  170000.0  213500.00  278000.0
Timber        242247.447368   64845.651549  137500.0  186900.00  228475.0
Veenker       238772.727273   72369.317959  162500.0  184250.00  218000.0


                    75%       max
Neighborhood
Blmngtn       213490.00  264561.0
Blueste       144250.00  151000.0
BrDale        118000.00  125000.0
BrkSide       141175.00  223500.0
ClearCr       242225.00  328000.0
CollgCr       225725.00  424870.0
Crawfor       239000.00  392500.0
Edwards       145225.00  320000.0
Gilbert       197200.00  377500.0
IDOTRR        120500.00  169500.0
MeadowV       115000.00  151400.0
Mitchel       171000.00  271000.0
NAmes         158000.00  345000.0
NPkVill       148500.00  155000.0
NWAmes        205000.00  299800.0
NoRidge       341000.00  755000.0
NridgHt       374000.00  611657.0
OldTown       140000.00  475000.0
SWISU         160000.00  200000.0
Sawyer        149462.50  190000.0
SawyerW       222500.00  320000.0
Somerst       252919.50  423000.0
StoneBr       377426.00  556581.0
Timber        286115.75  378500.0
Veenker       282000.00  385000.0

[25 rows x 304 columns]

In [ ]:
# Total home valuation of all houses in dataset
#
# Scenario: A real estate developer wants to know the total value of sales in
# general to gauge market activity and investment potential
total_valuation = df['SalePrice'].sum()
print("Total Valuation of houses: USD", total_valuation)
print()

# Total home valuation of each neighborhood
#
# Scenario: A real estate developer wants to know the total value of sales in
# each neighborhood to gauge market activity and investment potential
neighborhood_valuation = grouped_df['SalePrice'].sum()
neighborhood_valuation.name = "HomeValuation"
neighborhood_valuation

Total Valuation of houses: USD 264144946

Neighborhood
Blmngtn     3312805
Blueste      275000
BrDale      1671900
BrkSide     7240375
ClearCr     5951832
CollgCr    29694866
Crawfor    10741861
Edwards    12821970
Gilbert    15235506
IDOTRR      3704580
MeadowV     1675800
Mitchel     7657236
NAmes      32815593
NPkVill     1284250
NWAmes     13800655
NoRidge    13747108
NridgHt    24352838
OldTown    14489459
SWISU       3564784
Sawyer     10122692
SawyerW    11006792
Somerst    19382666
StoneBr     7762475
Timber      9205403
Veenker     2626500
Name: HomeValuation, dtype: int64

In [ ]:
# Average home price in the dataset
#
# Scenario: As a buyer I might want to know the average home prices to get a
# rough idea on the kind of budget I should have while going through the prices
average_price = df['SalePrice'].mean()
print("Average Price of houses: USD", average_price)

# Average home price in each neighborhood
#
# Scenario: As a buyer I might want to see the average home price in a given
# neighborhood to prioritize on those neighborhoods which are likely to be
# within my budget
average_price_neighborhood = grouped_df['SalePrice'].mean()
average_price_neighborhood.name = "AveragePrice"
average_price_neighborhood

Average Price of houses: USD 180921.19589041095

Neighborhood
Blmngtn    194870.882353
Blueste    137500.000000
BrDale     104493.750000
BrkSide    124834.051724
ClearCr    212565.428571
CollgCr    197965.773333
Crawfor    210624.725490
Edwards    128219.700000
Gilbert    192854.506329
IDOTRR     100123.783784
MeadowV     98576.470588
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
NWAmes     189050.068493
NoRidge    335295.317073
NridgHt    316270.623377
OldTown    128225.300885
SWISU      142591.360000
Sawyer     136793.135135
SawyerW    186555.796610
Somerst    225379.837209
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Name: AveragePrice, dtype: float64

In [ ]:
# Median home price in dataset
#
# Scenario: As a buyer I might want to know the average home prices to get a
# rough idea on the kind of budget I should have while going through the prices.
# (Similar to mean but using median here as an average instead)
median_price = df['SalePrice'].median()
print("Median Price of homes: USD", median_price)

# Median home price in each neighborhood
#
# Scenario: As a buyer I might want to know the average home prices to get a
# rough idea on the kind of budget I should have while going through the prices.
# (Similar to mean but using median here as an average instead)
median_price_neighborhood = grouped_df['SalePrice'].median()
median_price_neighborhood.name = "MedianPrice"
median_price_neighborhood

Median Price of homes: USD 163000.0

Neighborhood
Blmngtn    191000.0
Blueste    137500.0
BrDale     106000.0
BrkSide    124300.0
ClearCr    200250.0
CollgCr    197200.0
Crawfor    200624.0
Edwards    121750.0
Gilbert    181000.0
IDOTRR     103000.0
MeadowV     88000.0
Mitchel    153500.0
NAmes      140000.0
NPkVill    146000.0
NWAmes     182900.0
NoRidge    301500.0
NridgHt    315000.0
OldTown    119000.0
SWISU      139500.0
Sawyer     135000.0
SawyerW    179900.0
Somerst    225500.0
StoneBr    278000.0
Timber     228475.0
Veenker    218000.0
Name: MedianPrice, dtype: float64

In [ ]:
# Minimum sale price in dataset
#
# To know the cheapest home in the dataset
min_price = df['SalePrice'].min()
print("Minimum Price of homes: USD", min_price)

# Minimum sale price in each neighborhood
#
# To know the cheapest home in each neighborhood
min_price_neighborhood = grouped_df['SalePrice'].min()
min_price_neighborhood.name = "MinPrice"
min_price_neighborhood

Minimum Price of homes: USD 34900

Neighborhood
Blmngtn    159895
Blueste    124000
BrDale      83000
BrkSide     39300
ClearCr    130000
CollgCr    110000
Crawfor     90350
Edwards     58500
Gilbert    141000
IDOTRR      34900
MeadowV     75000
Mitchel     84500
NAmes       87500
NPkVill    127500
NWAmes      82500
NoRidge    190000
NridgHt    154000
OldTown     37900
SWISU       60000
Sawyer      62383
SawyerW     76000
Somerst    144152
StoneBr    170000
Timber     137500
Veenker    162500
Name: MinPrice, dtype: int64

In [ ]:
# Maximum sale price in dataset
#
# Scenario: A financially well off person wanting to know the most expensive
# home in the dataset to get an idea of the facilities they can get there
max_price = df['SalePrice'].max()
print("Maximum Price of homes: USD", max_price)

# Maximum sale price in each neighborhood
#
# Scenario: A person trying to know the most expensive house in each
# neighborhood
max_price_neighborhood = grouped_df['SalePrice'].max()
max_price_neighborhood.name = "Max Price"
max_price_neighborhood

Maximum Price of homes: USD 755000

Neighborhood
Blmngtn    264561
Blueste    151000
BrDale     125000
BrkSide    223500
ClearCr    328000
CollgCr    424870
Crawfor    392500
Edwards    320000
Gilbert    377500
IDOTRR     169500
MeadowV    151400
Mitchel    271000
NAmes      345000
NPkVill    155000
NWAmes     299800
NoRidge    755000
NridgHt    611657
OldTown    475000
SWISU      200000
Sawyer     190000
SawyerW    320000
Somerst    423000
StoneBr    556581
Timber     378500
Veenker    385000
Name: Max Price, dtype: int64

In [ ]:
# Scenario: To know the number of homes in the dataset
num_homes = df['SalePrice'].count()
print("Number of homes sold: ", num_homes)

# Number of homes present in each neighborhood
num_homes_neighborhood = grouped_df['SalePrice'].count()
num_homes_neighborhood.name = "No. of Homes"
num_homes_neighborhood

Number of homes sold:  1460

Neighborhood
Blmngtn     17
Blueste      2
BrDale      16
BrkSide     58
ClearCr     28
CollgCr    150
Crawfor     51
Edwards    100
Gilbert     79
IDOTRR      37
MeadowV     17
Mitchel     49
NAmes      225
NPkVill      9
NWAmes      73
NoRidge     41
NridgHt     77
OldTown    113
SWISU       25
Sawyer      74
SawyerW     59
Somerst     86
StoneBr     25
Timber      38
Veenker     11
Name: No. of Homes, dtype: int64

In [ ]:
# Standard deviation of all prices in the dataset
#
# Scenario: A person viewing the dataset might want to get an idea of how
# much do the prices in the dataset vary in general
std_price = df['SalePrice'].std()
print("Standard Deviation of prices: USD", std_price)

# Standard deviation of prices in each neighborhood
#
# Scenario: A financial analyst might want to know the volatility of prices
# in a neighborhood to know how similar the house are there
std_price_neighborhood = grouped_df['SalePrice'].std()
std_price_neighborhood.name = "SD"
std_price_neighborhood

Standard Deviation of prices: USD 79442.50288288663

Neighborhood
Blmngtn     30393.229219
Blueste     19091.883092
BrDale      14330.176493
BrkSide     40348.689270
ClearCr     50231.538993
CollgCr     51403.666438
Crawfor     68866.395472
Edwards     43208.616459
Gilbert     35986.779085
IDOTRR      33376.710117
MeadowV     23491.049610
Mitchel     36486.625334
NAmes       33075.345450
NPkVill      9377.314529
NWAmes      37172.218106
NoRidge    121412.658640
NridgHt     96392.544954
OldTown     52650.583185
SWISU       32622.917679
Sawyer      22345.129157
SawyerW     55651.997820
Somerst     56177.555888
StoneBr    112969.676640
Timber      64845.651549
Veenker     72369.317959
Name: SD, dtype: float64

In [ ]:
# Variance of prices in dataset
#
# Similar to standard deviation, but variance is more often used for its math
# property of additivity of variance. Standard deviation is more interpretable
# in general otherwise.
var_price = df['SalePrice'].var()
print("Variance of prices: USD", var_price)

# Variance of prices in each neighborhood
#
# Similar to standard deviation, but variance is more often used for its math
# property of additivity of variance. Standard deviation is more interpretable
# in general otherwise.
var_price_neighborhood = grouped_df['SalePrice'].var()
var_price_neighborhood.name = "Variance"
var_price_neighborhood

Variance of prices: USD 6311111264.297451

Neighborhood
Blmngtn    9.237484e+08
Blueste    3.645000e+08
BrDale     2.053540e+08
BrkSide    1.628017e+09
ClearCr    2.523208e+09
CollgCr    2.642337e+09
Crawfor    4.742580e+09
Edwards    1.866985e+09
Gilbert    1.295048e+09
IDOTRR     1.114005e+09
MeadowV    5.518294e+08
Mitchel    1.331274e+09
NAmes      1.093978e+09
NPkVill    8.793403e+07
NWAmes     1.381774e+09
NoRidge    1.474103e+10
NridgHt    9.291523e+09
OldTown    2.772084e+09
SWISU      1.064255e+09
Sawyer     4.993048e+08
SawyerW    3.097145e+09
Somerst    3.155918e+09
StoneBr    1.276215e+10
Timber     4.204959e+09
Veenker    5.237318e+09
Name: Variance, dtype: float64

In [ ]:
# Get the number of neighborhoods in the data
print("Number of neighborhoods in the dataset:", df["Neighborhood"].nunique())

# Checking the possibility of an sell out event in a neighborhood for further
# investigation
print("\nNumber of houses sold in different years in neighborhood:")
grouped_df["YrSold"].nunique()

Number of neighborhoods in the dataset: 25

Number of houses sold in different years in neighborhood:

Neighborhood
Blmngtn    5
Blueste    2
BrDale     5
BrkSide    5
ClearCr    5
CollgCr    5
Crawfor    5
Edwards    5
Gilbert    5
IDOTRR     5
MeadowV    5
Mitchel    5
NAmes      5
NPkVill    4
NWAmes     5
NoRidge    5
NridgHt    5
OldTown    5
SWISU      5
Sawyer     5
SawyerW    5
Somerst    5
StoneBr    5
Timber     5
Veenker    3
Name: YrSold, dtype: int64

In [ ]:
# Get a rough idea of how old streets (can be used in conjuction with
# filtering when years are above/below threshold of interest)
first_sale_event = grouped_df["YearBuilt"].min()
first_sale_event.name = "FirstSaleEventYear"
display(first_sale_event)

# Similarly, one would want to investigate about most recent events so they
# could
last_sale_event = grouped_df["YearBuilt"].max()
last_sale_event.name = "LatestSaleEventYear"
display(last_sale_event)

Neighborhood
Blmngtn    2003
Blueste    1980
BrDale     1970
BrkSide    1908
ClearCr    1908
CollgCr    1969
Crawfor    1910
Edwards    1900
Gilbert    1948
IDOTRR     1900
MeadowV    1970
Mitchel    1940
NAmes      1918
NPkVill    1974
NWAmes     1963
NoRidge    1990
NridgHt    2003
OldTown    1872
SWISU      1911
Sawyer     1875
SawyerW    1928
Somerst    1997
StoneBr    1984
Timber     1948
Veenker    1974
Name: FirstSaleEventYear, dtype: int64

Neighborhood
Blmngtn    2007
Blueste    1980
BrDale     1973
BrkSide    1970
ClearCr    1997
CollgCr    2009
Crawfor    2008
Edwards    2009
Gilbert    2007
IDOTRR     1963
MeadowV    1977
Mitchel    2007
NAmes      1998
NPkVill    1978
NWAmes     2001
NoRidge    2001
NridgHt    2009
OldTown    2003
SWISU      1940
Sawyer     1982
SawyerW    2005
Somerst    2009
StoneBr    2010
Timber     2009
Veenker    1996
Name: LatestSaleEventYear, dtype: int64

In [ ]:
# Calculating
# Scenario: A loan officer wants to understand the central tendency of home prices in a way that is robust to outliers, helping them assess risk.
quantile_result = grouped_df['SalePrice'].quantile(0.5)
display(quantile_result)

Neighborhood
Blmngtn    191000.0
Blueste    137500.0
BrDale     106000.0
BrkSide    124300.0
ClearCr    200250.0
CollgCr    197200.0
Crawfor    200624.0
Edwards    121750.0
Gilbert    181000.0
IDOTRR     103000.0
MeadowV     88000.0
Mitchel    153500.0
NAmes      140000.0
NPkVill    146000.0
NWAmes     182900.0
NoRidge    301500.0
NridgHt    315000.0
OldTown    119000.0
SWISU      139500.0
Sawyer     135000.0
SawyerW    179900.0
Somerst    225500.0
StoneBr    278000.0
Timber     228475.0
Veenker    218000.0
Name: SalePrice, dtype: float64

In [ ]:
# There are different ways one could aggregate multiple aggregation functions

In [ ]:
# Applying Multiple Aggregations to a Single Column
#
# Scenario: A real estate analyst needs a single summary table to see the total,
# average, and maximum sale price for each neighborhood for a quarterly market report.
multiple_agg_result = grouped_df['SalePrice'].agg(['sum', 'mean', 'max'])
multiple_agg_result

                   sum           mean     max
Neighborhood
Blmngtn        3312805  194870.882353  264561
Blueste         275000  137500.000000  151000
BrDale         1671900  104493.750000  125000
BrkSide        7240375  124834.051724  223500
ClearCr        5951832  212565.428571  328000
CollgCr       29694866  197965.773333  424870
Crawfor       10741861  210624.725490  392500
Edwards       12821970  128219.700000  320000
Gilbert       15235506  192854.506329  377500
IDOTRR         3704580  100123.783784  169500
MeadowV        1675800   98576.470588  151400
Mitchel        7657236  156270.122449  271000
NAmes         32815593  145847.080000  345000
NPkVill        1284250  142694.444444  155000
NWAmes        13800655  189050.068493  299800
NoRidge       13747108  335295.317073  755000
NridgHt       24352838  316270.623377  611657
OldTown       14489459  128225.300885  475000
SWISU          3564784  142591.360000  200000
Sawyer        10122692  136793.135135  190000
SawyerW       11006792  186555.796610  320000
Somerst       19382666  225379.837209  423000
StoneBr        7762475  310499.000000  556581
Timber         9205403  242247.447368  378500
Veenker        2626500  238772.727273  385000

In [ ]:
# Applying Different Aggregations to Different Columns
#
# Scenario: A performance dashboard needs to display the total and average home
# price for each neighborhood while also showing the minimum and maximum number
# of bedrooms sold in a single, comprehensive table.
different_agg_result = grouped_df.agg({
    'SalePrice': ['sum', 'mean'], # Total, mean
    'YrSold': ['min', 'max'], # Sales activity duration
})
different_agg_result

             SalePrice                YrSold
                   sum           mean    min   max
Neighborhood
Blmngtn        3312805  194870.882353   2006  2010
Blueste         275000  137500.000000   2008  2009
BrDale         1671900  104493.750000   2006  2010
BrkSide        7240375  124834.051724   2006  2010
ClearCr        5951832  212565.428571   2006  2010
CollgCr       29694866  197965.773333   2006  2010
Crawfor       10741861  210624.725490   2006  2010
Edwards       12821970  128219.700000   2006  2010
Gilbert       15235506  192854.506329   2006  2010
IDOTRR         3704580  100123.783784   2006  2010
MeadowV        1675800   98576.470588   2006  2010
Mitchel        7657236  156270.122449   2006  2010
NAmes         32815593  145847.080000   2006  2010
NPkVill        1284250  142694.444444   2007  2010
NWAmes        13800655  189050.068493   2006  2010
NoRidge       13747108  335295.317073   2006  2010
NridgHt       24352838  316270.623377   2006  2010
OldTown       14489459  128225.300885   2006  2010
SWISU          3564784  142591.360000   2006  2010
Sawyer        10122692  136793.135135   2006  2010
SawyerW       11006792  186555.796610   2006  2010
Somerst       19382666  225379.837209   2006  2010
StoneBr        7762475  310499.000000   2006  2010
Timber         9205403  242247.447368   2006  2010
Veenker        2626500  238772.727273   2006  2008