In [2]:
# Download the dataset file to local storage (from publicly shared drive file)
# Original source: https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques
# (The rest of the notebook expects the original housing.csv to be present in the current directory)
!gdown 1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP

Downloading...
From: https://drive.google.com/uc?id=1Yhw8tBCmjYrDZ5Rm1xPrP2y5bmBmxoEP
To: /content/housing.csv
100% 461k/461k [00:00<00:00, 48.6MB/s]

In [3]:
import pandas as pd
df = pd.read_csv(r"/content/housing.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
display(df)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
# Display all the number of nan values in each column and type
column_stats_raw = []

for column_name in df.columns:
  column_stats_raw.append((column_name, df[column_name].dtype, df[column_name].isna().sum()))
column_stats_raw

column_stats_df = pd.DataFrame(column_stats_raw, columns=['Column name', 'Type', 'Number of null values'])
print(column_stats_df)

column_stats_df.sort_values(by ='Number of null values', ascending = False, inplace = True)

print(column_stats_df.to_string())

      Column name     Type  Number of null values
0              Id    int64                      0
1      MSSubClass    int64                      0
2        MSZoning   object                      0
3     LotFrontage  float64                    259
4         LotArea    int64                      0
..            ...      ...                    ...
76         MoSold    int64                      0
77         YrSold    int64                      0
78       SaleType   object                      0
79  SaleCondition   object                      0
80      SalePrice    int64                      0

[81 rows x 3 columns]
      Column name     Type  Number of null values
72         PoolQC   object                   1453
74    MiscFeature   object                   1406
6           Alley   object                   1369
73          Fence   object                   1179
25     MasVnrType   object                    872
57    FireplaceQu   object                    690
3     LotFrontage  float64                    259
63     GarageQual   object                     81
60   GarageFinish   object                     81
58     GarageType   object                     81
59    GarageYrBlt  float64                     81
64     GarageCond   object                     81
35   BsmtFinType2   object                     38
32   BsmtExposure   object                     38
31       BsmtCond   object                     37
30       BsmtQual   object                     37
33   BsmtFinType1   object                     37
26     MasVnrArea  float64                      8
42     Electrical   object                      1
14     Condition2   object                      0
15       BldgType   object                      0
12   Neighborhood   object                      0
11      LandSlope   object                      0
10      LotConfig   object                      0
13     Condition1   object                      0
8     LandContour   object                      0
7        LotShape   object                      0
5          Street   object                      0
4         LotArea    int64                      0
1      MSSubClass    int64                      0
2        MSZoning   object                      0
0              Id    int64                      0
9       Utilities   object                      0
16     HouseStyle   object                      0
29     Foundation   object                      0
27      ExterQual   object                      0
28      ExterCond   object                      0
37      BsmtUnfSF    int64                      0
38    TotalBsmtSF    int64                      0
39        Heating   object                      0
34     BsmtFinSF1    int64                      0
24    Exterior2nd   object                      0
23    Exterior1st   object                      0
22       RoofMatl   object                      0
21      RoofStyle   object                      0
20   YearRemodAdd    int64                      0
17    OverallQual    int64                      0
19      YearBuilt    int64                      0
18    OverallCond    int64                      0
48   BsmtHalfBath    int64                      0
47   BsmtFullBath    int64                      0
46      GrLivArea    int64                      0
45   LowQualFinSF    int64                      0
44       2ndFlrSF    int64                      0
43       1stFlrSF    int64                      0
41     CentralAir   object                      0
40      HeatingQC   object                      0
36     BsmtFinSF2    int64                      0
56     Fireplaces    int64                      0
54   TotRmsAbvGrd    int64                      0
53    KitchenQual   object                      0
52   KitchenAbvGr    int64                      0
55     Functional   object                      0
49       FullBath    int64                      0
50       HalfBath    int64                      0
61     GarageCars    int64                      0
62     GarageArea    int64                      0
51   BedroomAbvGr    int64                      0
65     PavedDrive   object                      0
68  EnclosedPorch    int64                      0
69      3SsnPorch    int64                      0
67    OpenPorchSF    int64                      0
66     WoodDeckSF    int64                      0
71       PoolArea    int64                      0
70    ScreenPorch    int64                      0
75        MiscVal    int64                      0
76         MoSold    int64                      0
77         YrSold    int64                      0
78       SaleType   object                      0
79  SaleCondition   object                      0
80      SalePrice    int64                      0

In [ ]:
# Deletion of rows with missing data

# Scenario: We are trying to test the correlation between LotFrontage and SalePrice,
# therefore we remove the rows that have NA values for them
df.dropna(subset=["LotFrontage", "SalePrice"])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
column_stats_raw = []
for column_name in df.columns:
  column_stats_raw.append((column_name, df[column_name].dtype, df[column_name].isna().sum()))

column_stats_df = pd.DataFrame(column_stats_raw, columns=['Column name', 'Type', 'Number of null values'])
column_stats_df.sort_values(by ='Number of null values', ascending = False, inplace = True)

print(column_stats_df.to_string())

      Column name     Type  Number of null values
72         PoolQC   object                   1453
74    MiscFeature   object                   1406
6           Alley   object                   1369
73          Fence   object                   1179
25     MasVnrType   object                    872
57    FireplaceQu   object                    690
3     LotFrontage  float64                    259
63     GarageQual   object                     81
60   GarageFinish   object                     81
58     GarageType   object                     81
59    GarageYrBlt  float64                     81
64     GarageCond   object                     81
35   BsmtFinType2   object                     38
32   BsmtExposure   object                     38
31       BsmtCond   object                     37
30       BsmtQual   object                     37
33   BsmtFinType1   object                     37
26     MasVnrArea  float64                      8
42     Electrical   object                      1
14     Condition2   object                      0
15       BldgType   object                      0
12   Neighborhood   object                      0
11      LandSlope   object                      0
10      LotConfig   object                      0
13     Condition1   object                      0
8     LandContour   object                      0
7        LotShape   object                      0
5          Street   object                      0
4         LotArea    int64                      0
1      MSSubClass    int64                      0
2        MSZoning   object                      0
0              Id    int64                      0
9       Utilities   object                      0
16     HouseStyle   object                      0
29     Foundation   object                      0
27      ExterQual   object                      0
28      ExterCond   object                      0
37      BsmtUnfSF    int64                      0
38    TotalBsmtSF    int64                      0
39        Heating   object                      0
34     BsmtFinSF1    int64                      0
24    Exterior2nd   object                      0
23    Exterior1st   object                      0
22       RoofMatl   object                      0
21      RoofStyle   object                      0
20   YearRemodAdd    int64                      0
17    OverallQual    int64                      0
19      YearBuilt    int64                      0
18    OverallCond    int64                      0
48   BsmtHalfBath    int64                      0
47   BsmtFullBath    int64                      0
46      GrLivArea    int64                      0
45   LowQualFinSF    int64                      0
44       2ndFlrSF    int64                      0
43       1stFlrSF    int64                      0
41     CentralAir   object                      0
40      HeatingQC   object                      0
36     BsmtFinSF2    int64                      0
56     Fireplaces    int64                      0
54   TotRmsAbvGrd    int64                      0
53    KitchenQual   object                      0
52   KitchenAbvGr    int64                      0
55     Functional   object                      0
49       FullBath    int64                      0
50       HalfBath    int64                      0
61     GarageCars    int64                      0
62     GarageArea    int64                      0
51   BedroomAbvGr    int64                      0
65     PavedDrive   object                      0
68  EnclosedPorch    int64                      0
69      3SsnPorch    int64                      0
67    OpenPorchSF    int64                      0
66     WoodDeckSF    int64                      0
71       PoolArea    int64                      0
70    ScreenPorch    int64                      0
75        MiscVal    int64                      0
76         MoSold    int64                      0
77         YrSold    int64                      0
78       SaleType   object                      0
79  SaleCondition   object                      0
80      SalePrice    int64                      0

In [ ]:
# Mean/Median Imputation

# We are considering LotFrontage again as it is in float (numerical) and has null values

meanLotFrontage = df["LotFrontage"].mean()
medianLotFrontage = df["LotFrontage"].median()

meanImputedLotFrontage = df["LotFrontage"].fillna(meanLotFrontage)
medianImputedLotFrontage = df["LotFrontage"].fillna(medianLotFrontage)

# Showing all values might not be the best option here given the size,
# therefore using mean/median to show that math is maintained

print("Mean before performing mean imputation:", meanLotFrontage)
print("Mean after performing mean imputation:", meanImputedLotFrontage.mean())
print()
print("Median before performing median imputation:", medianLotFrontage)
print("Median after performing median imputation:", medianImputedLotFrontage.median())
print()
print("Both are almost the same/maintained because of the kind of imputation performed here.")

Mean before performing mean imputation: 70.04995836802665
Mean after performing mean imputation: 70.04995836802664

Median before performing median imputation: 69.0
Median after performing median imputation: 69.0

Both are almost the same/maintained because of the kind of imputation performed here.

In [ ]:
# Mode imputation
# (Can be considered in cases of non-numeric values where mean/median averaging isn't possible)

print("Unique values of BsmtQual/Basement Quality column:", set(df["BsmtQual"]))

uniqueBsmtQuals = set(df["BsmtQual"])
print(df["BsmtQual"].mode())


# Multiple modes can exist if max count is same, therefore considering only the first one for imputation
modeBsmtQual = df["BsmtQual"].mode()[0]

print("Most repeated value of BsmtQual column:", modeBsmtQual)

print()
print("Current number of NaN values in BsmtQual:", df["BsmtQual"].isna().sum())

modeImputedBsmtQual = df["BsmtQual"].fillna(modeBsmtQual)

print("After imputation, the number of NaN values now are,", modeImputedBsmtQual.isna().sum())

Unique values of BsmtQual/Basement Quality column: {'Ex', 'TA', 'Fa', nan, 'Gd'}
0    TA
Name: BsmtQual, dtype: object
Most repeated value of BsmtQual column: TA

Current number of NaN values in BsmtQual: 37
After imputation, the number of NaN values now are, 0

In [ ]:
# Arbitrary value imputation (remaining)
# (Value chosen by analyst with his domain knowledge or their understanding of the dataset)

# For example, we could choose

arbitary_value = 21.0

print("Mean of LotFrontage before arbitrary value imputation:", df["LotFrontage"].mean())
arbitaryValueImputedCol = df["LotFrontage"].fillna(arbitary_value)
print("Mean of LotFrontage after arbitrary value imputation: ", arbitaryValueImputedCol.mean())

Mean of LotFrontage before arbitrary value imputation: 70.04995836802665
Mean of LotFrontage after arbitrary value imputation:  61.3486301369863

In [ ]:
# End of tail Imputation
minLotFrontage = df["LotFrontage"].min()
maxLotFrontage = df["LotFrontage"].max()

chosenTail = minLotFrontage
print("Chosen tail value:", chosenTail)

print("Mean before end of tail imputation:", df["LotFrontage"].mean())
tailImputedLotFrontage = df["LotFrontage"].fillna(chosenTail)
print("Mean after end of tail imputation:", tailImputedLotFrontage.mean())

Chosen tail value: 21.0
Mean before end of tail imputation: 70.04995836802665
Mean after end of tail imputation: 61.3486301369863

In [ ]:
# Random sample imputation (runtime error with logic)
import random

print("NaN values in FireplaceQu before sampling imputation:", df["FireplaceQu"].isna().sum())

# Random sample Imputation (on Fireplace Quality column)
random_sample_size = 10
random_sample = df["FireplaceQu"].dropna().sample(n=random_sample_size)

impute_random_sample = lambda x: random_sample.sample().iloc[0] if pd.isnull(x) else x

# Apply the lambda function to impute missing values in the "FireplaceQu" column
random_sample_imputed_col = df["FireplaceQu"].apply(impute_random_sample)

print("NaN values in FireplaceQu after sampling imputation: ", random_sample_imputed_col.isna().sum())

NaN values in FireplaceQu before sampling imputation: 690
NaN values in FireplaceQu after sampling imputation:  0

In [ ]:
#	Frequent category Imputation (same as mode imputation)
print("Unique values of GarageType column:", set(df["GarageType"]))

# Multiple modes can exist if max count is same, therefore considering only the first one for imputation
modeGarageType = df["GarageType"].mode()[0]

print("Most repeated value of GarageType column:", modeGarageType)

print()
print("Current number of NaN values in BsmtQual:", df["GarageType"].isna().sum())
freqCatImputatedCol = df["GarageType"].fillna(modeGarageType)
print("After imputation, the number of NaN values now are:", freqCatImputatedCol.isna().sum())

Unique values of GarageType column: {'Detchd', nan, 'Basment', 'CarPort', 'BuiltIn', 'Attchd', '2Types'}
Most repeated value of GarageType column: Attchd

Current number of NaN values in BsmtQual: 81
After imputation, the number of NaN values now are: 0

In [ ]:
# Adding a new category as "missing"
# (Replacing NaN values with explicit category such as "missing" as a common category for them)

missing_category = "Unknown"

print("Set of unique values in GarageType col before given imputation:", set(df["GarageType"]))
imputedColumn = df["GarageType"].fillna(missing_category)
print("Set of unique values in GarageType col after given imputation:", set(imputedColumn))

Set of unique values in GarageType col before given imputation: {'Detchd', nan, 'Basment', 'CarPort', 'BuiltIn', 'Attchd', '2Types'}
Set of unique values in GarageType col after given imputation: {'Detchd', 'Basment', 'CarPort', 'Unknown', 'BuiltIn', 'Attchd', '2Types'}

In [ ]:
# Random sample imputation (done earlier/repetition)

In [ ]:
# Regression
# We'll be using SalePrice (x) to predict LotFrontage (y) for missing/nan values
from sklearn.linear_model import LinearRegression

model = LinearRegression()
imputed_df = df.dropna(subset=["LotFrontage"])[["LotFrontage", "SalePrice"]]
X = imputed_df.SalePrice.values.reshape(len(imputed_df), 1)
Y = imputed_df.LotFrontage.values.reshape(len(imputed_df), 1)
model.fit(X, Y)

regression_imputed_lot_frontage = df[["LotFrontage", "SalePrice"]].apply(lambda x: model.predict([[x["SalePrice"]]])[0][0] if pd.isnull(x["LotFrontage"]) else x["LotFrontage"], axis=1)

print("Mean before regression imputation of LotFrontage:", df["LotFrontage"].mean())
print("Number NA values before imputation:", df["LotFrontage"].isna().sum())
print()
print("Mean after regression imputation of LotFrontage:", regression_imputed_lot_frontage.mean())

Mean before regression imputation of LotFrontage: 70.04995836802665
Number NA values before imputation: 259

Mean after regression imputation of LotFrontage: 70.065399342723